MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: build_alexnet_backbone
    ARCH_CFG: "pytorch"
    BN: False
    SOBEL: False
    FREEZE_AT: 1
    FREEZE_BN: False
  RPN:
    IN_FEATURES: ["features"]
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["features"]
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: FastRCNNConvFCHead
    NUM_CONV: 2
    CONV_DIM: 512
    NUM_FC: 0
    FC_DIM: 0
    NORM: "BN"
    POOLER_RESOLUTION: 7
  PIXEL_MEAN: [123.675,116.28,103.53]
  PIXEL_STD: [58.395,57.12,57.375]
  WEIGHTS: ""
  MASK_ON: False
  KEYPOINT_ON: False
DATASETS:
  TRAIN: ('voc_2007_train',)
  TEST: ('voc_2007_val',)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
  STEPS: (50000,80000)
  MAX_ITER: 100000
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0005
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
SEED: 36
